### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by ljk1072911239** [spytensor/detect_steel_bar#13]
when I input "**bash build.sh**", it occurs this error:
Compiling nms kernels by nvcc...
Including CUDA code.
/home/ljk/PycharmProjects/detect_steel_bar-master/retinanet/lib/nms
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    extra_compile_args=['-std=c99']
  File "/home/ljk/miniconda3/envs/pt04/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/ljk/miniconda3/envs/pt04/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
**TypeError: dist must be a Distribution instance**
what I should do?Thanks

**Comment by Hersue** [comment]
Hi, I met the same problem now. Do you find the solving method yet?

**Comment by xmy0916** [comment]
Hi, I met the same problem now. Do you find the solving method yet?

**Comment by chen-zhoujian** [comment]
Hi, I met the same problem now. Do you find the solving method yet?

**Comment by xmy0916** [comment]
> Hi, I met the same problem now. Do you find the solving method yet?
没有且放弃

**Comment by kingStar1006** [comment]
怎么搞
